export const flatePermissions = [
  'permission.footerMenu-list',
  'permission.footerMenu-item',
  'permission.create',
  'permission.update',
  'permission.delete',
  'role.footerMenu-list',
  'role.footerMenu-item',
  'role.create',
  'role.update',
  'role.delete',
  'user.footerMenu-list',
  'user.footerMenu-item',
  'user.create',
  'user.update',
  'user.delete',
];
