export enum IModuleNameEnum {
  article = 'article',
  config = 'config',
  seed = 'seed',
  playground = 'playground',
  index = 'index',
  //
  auth = 'auth',
  user = 'user',
  permission = 'permission',
  role = 'role',
  category = 'category',
  action = 'action',
  attachment = 'attachment',
  ax = 'ax',
  authtoken = 'authtoken',
  setting = 'setting',
  tag = 'tag',
  coupon = 'coupon',
  promo = 'promo',
  product = 'product',
  address = 'address',
  division = 'division',
  export = 'export',
  zan = 'zan',
  test = 'test',
  i18n = 'i18n',
}
