export const HTTP_ERROR_SUFFIX = 'Faild';
export const HTTP_SUCCESS_SUFFIX = 'Success';
export const HTTP_DEFAULT_TEXT = 'Fetch Data ';
export const HTTP_DEFAULT_ERROR_TEXT = HTTP_DEFAULT_TEXT + HTTP_ERROR_SUFFIX;
export const HTTP_DEFAULT_SUCCESS_TEXT = HTTP_DEFAULT_TEXT + HTTP_SUCCESS_SUFFIX;

export const HTTP_ANONYMOUSE_TEXT = 'ANONYMOUSE';
export const HTTP_UNAUTHORIZED_TEXT = 'UNAUTHORIZED';
export const HTTP_BAD_REQUEST_TEXT = 'BAD_REQUEST';
export const HTTP_PARAMS_PERMISSION_ERROR = 'PARAMS_PERMISSION_ERROR';

export const VALIDATION_ERROR = 'VALIDATION_ERROR';
