export interface IDotEnv {
  SERVER_NAME: string;
  SERVER_PROTOCOL: string;
  SERVER_PORT: number;
  SERVER_HOST: string;

  DEMO_MODE: string;
  DEBUG_MODE: string;

  PUBLIC_DIR: string;
  GRAVATAR_TYPE: string;

  ATTACHMENT_DIR: string;
  ATTACHMENT_LIMIT_SIZE_MB: number;
  ATTACHMENT_SAVE_IN_LOCAL: string;
  ATTACHMENT_SAVE_IN_OSS: string;

  DB_TYPE: string;
  DB_HOST: string;
  DB_PORT: number;
  DB_USERNAME: string;
  DB_PASSWORD: string;
  DB_DATABASE: string;
  DB_SYNCHRONIZE: string;

  RATELIMIT_WINDOWMS: number;
  RATELIMIT_MAX: number;

  ENABLE_CAPTCHA_BY_LOGIN_FAILD_TIMES: number;

  TRUST_PROXY: string;
  JWT_SECRET_KEY: string;
  CLIENT_COOKIE_EXPIRES_SECOND: number;
  SERVER_COOKIE_EXPIRES_SECOND: number;

  ATTACHMENT_OSS_ALIYUN_BUCKET?: string;
  ATTACHMENT_OSS_ALIYUN_AK_SECRET?: string;
  ATTACHMENT_OSS_ALIYUN_AK_ID?: string;
  ATTACHMENT_OSS_ALIYUN_REGION?: string;
  ATTACHMENT_OSS_ALIYUN_CALLBACK_URL?: string;

  OAUTH_WECHAT_APP_ID?: string;
  OAUTH_WECHAT_APP_SECRET?: string;
  OAUTH_WECHAT_MINIPROGRAM_APP_ID?: string;
  OAUTH_WECHAT_MINIPROGRAM_APP_SECRET?: string;
  OAUTH_WECHAT_TOKEN?: string;
  OAUTH_WECHAT_CALLBACK_URL?: string;

  OAUTH_GITHUB_CLIENT_ID?: string;
  OAUTH_GITHUB_CLIENT_SECRET?: string;
  OAUTH_GITHUB_CALLBACK_URL?: string;
}

export interface IBuild {
  MODE: string;
  LANG: string;
  VERSION: string;
  BUILDTIME: string;
}
